require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/tweets', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Tweet. As you add validations to Tweet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { body: 'this is a tweet' }
  end

  let(:user) { create(:user) }
  let(:tweet) { create(:tweet) }
  before { sign_in user }

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /show' do
    it 'successfully shows the tweet page' do
      get tweet_path(tweet)
      expect(response).to have_http_status(:success)
    end

    it 'increases the View Count if the tweet has not been viewed' do
      expect { get tweet_path(tweet) }.to change { View.count }.by(1)
    end

    it 'does not increase the View Count if the tweet has already been viewed' do
      create(:view, user:, tweet:)
      expect { get tweet_path(tweet) }.not_to change { View.count }
    end
  end

  describe 'POST /create' do
    context 'when user signed out' do
      it 'redirects to sign in' do
        post tweets_path, params: { tweet: valid_attributes }
        expect(response).to have_http_status(:redirect)
      end
    end

    context 'when user signed in' do
      it 'successfully posts the tweet' do
        user = create(:user)
        sign_in user
        expect do
          post tweets_path, params: { tweet: valid_attributes }
        end.to change { Tweet.count && PublicActivity::Activity.count }.by(1)
        expect(response).to redirect_to(dashboard_path)
      end
    end
  end
end
